### ISSUE TITLE
Improve Error Messages

### ISSUE THREAD

**Issue by fwilhe** [osiam/shell#10]
Currently, most "wrong" user input triggers a stack-trace. This is not a sign of a good user interface. It would be way better to catch common cases and tell the user what is wrong.

This can be reproduced by

```
osiam-shell/localhost/@admin> search-users foo
de.raysha.lib.jsimpleshell.exception.CLIException: org.osiam.client.exception.ConflictException: no viable alternative at input 'foo'
	at de.raysha.lib.jsimpleshell.ShellCommand.invoke(ShellCommand.java:77)
...
```

**Comment by sschum** [comment]
If an exception is thrown from a command the JSimpleShell will print it (inclusive the stacktrace). To prevent this issue we have to catch such exceptions and print out a custom message. Or we can implement a (aux)handler that can convert the exceptions to human readable messages. Look at [this example](https://github.com/rainu/jsimpleshell/tree/master/examples/io-converter) to find out how it works.

**Comment by sputnik27** [comment]
I implemented a `Converter`, but it does not get triggered when an `Exception` is thrown.. Is there anything I am missing?

Diff: https://github.com/osiam/shell/compare/master...sputnik27:improve-error-messages

**Comment by sschum** [comment]
Looks good to me. Maybe its an issue in JSS.
