### ISSUE TITLE
Better Tab Completion

### ISSUE THREAD

**Issue by fwilhe** [osiam/shell#11]
Tab-completion is not ideal at the moment. For example, when I don't know what arguments a command takes, I am forced to use `?help command`. It would be much nicer to imitate the behavior of zsh or bash.

For example
```
osiam-shell/localhost/@admin> search-users <TAB> <TAB>
```

should tell me which arguments `search-users` accepts.

**Comment by sschum** [comment]
There is no support in [JSimpleShell](https://github.com/rainu/jsimpleshell) (especially [JLine2](https://github.com/jline/jline2)) to use the double-tab. Auto completion with tab is done by the JLine2 automatically.  But we should check if there is an other way to support the user with auto completion. For example: we can auto complete the user-ids and so on.

Look [this example](https://github.com/rainu/jsimpleshell/tree/master/examples/autocomplete) to find out how the auto completion works.
