### ISSUE TITLE
Migrate to Gradle

### ISSUE THREAD

**Issue by fwilhe** [osiam/shell#13]
As discussed in #3, we might benefit from migrating the project to [gradle](http://gradle.org/).

Note that the [init plugin](https://docs.gradle.org/current/userguide/build_init_plugin.html) provides some automation for this.

**Comment by sputnik27** [comment]
I think I found a bug in the gradle shadow plugin, see [this issue](https://github.com/johnrengelman/shadow/issues/155).

If there is no solution for this in the foreseeable future, we'll have to look for an alternative way.

**Comment by dacrome** [comment]
The osiam shell is migrated to gradle, so I think we can close this issue, right?

**Comment by fwilhe** [comment]
I think so.
