### ISSUE TITLE
Persist Session Information

### ISSUE THREAD

**Issue by fwilhe** [osiam/shell#17]
It would be nice to be able to persist `connect` and `login` information on file. This would permit a more convenient use of the shell for a once set up connection.

**Comment by sschum** [comment]
At the moment the user can use the macro function:
$> !start-record connectToOsiam
$> connect <informations>
$> !stop-record
$> !run-macro connectToOsiam

Macros are stored in the macro-home-folder. One macro is easily a file where all commands included in.
