### ISSUE TITLE
add a distribution artifact

### ISSUE THREAD

**Issue by tkrille** [osiam/shell#3]
as previously started to be discussed here: https://github.com/osiam/distribution/issues/12

summary (this is my point of view): we should release distribution archives of the shell including at least a start script or other supporting files. this distribution could then be included in the OSIAM [main distribution](https://github.com/osiam/distribution).

**Comment by sputnik27** [comment]
Just for discussion: If we migrate the project to gradle (which is a goal for OSIAM in general), we could use the [application plugin](https://docs.gradle.org/current/userguide/application_plugin.html) and its `startScripts`-task. Would that not solve the issue, @tkrille?

Besides, migrating this particular project to gradle should not be that much work, if I don't overlook a very heavy blocker-task.

**Comment by tkrille** [comment]
@sputnik27 I'm not that familiar with the application plugin but it seems it would solve this issue. I don't see any problems in a migration to Gradle.
