### ISSUE TITLE
HowTo is Missing

### ISSUE THREAD

**Issue by fwilhe** [osiam/shell#9]
The README.md should contain (at least) a minimal amount of instructions on how to use the shell.

**Comment by tkrille** [comment]
@sschum You have time for this?

**Comment by sputnik27** [comment]
FYI: I began working on this in my private fork, but at the moment I don't understand enough of it to write a really useful README. You can have a look at it here https://github.com/sputnik27/shell/tree/write-user-documentation

**Comment by sputnik27** [comment]
> @sschum You have time for this?

Would be nice to know. My knowledge is not yet deep enough to write a decent README.
